copy %MAGICK_HOME%\VisualMagick\bin\CORE_DB_magick_.dll %1
copy "%MAGICK_HOME%\VisualMagick\bin\CORE_DB_Magick++_.dll" %1
copy %MAGICK_HOME%\VisualMagick\bin\CORE_DB_png_.dll %1
copy %MAGICK_HOME%\VisualMagick\bin\CORE_DB_wand_.dll %1
copy %MAGICK_HOME%\VisualMagick\bin\IM_MOD_DB_bmp_.dll %1
copy %MAGICK_HOME%\VisualMagick\bin\IM_MOD_DB_jpeg_.dll %1
copy %MAGICK_HOME%\VisualMagick\bin\IM_MOD_DB_png_.dll %1
copy %MAGICK_HOME%\VisualMagick\bin\IM_MOD_DB_tiff_.dll %1
copy %MAGICK_HOME%\VisualMagick\bin\IM_MOD_DB_webp_.dll %1
